Django_Jobs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('', include('website.urls')),
    path("admin/", admin.site.urls),
    path('accounts/', include('users.urls')),
    path('company/', include('company.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('resume/',include('resume.urls')),
    path('job/',include('job.urls')),
    path('resume/',include('resume.urls')),
    path('notifications/',include('notifications.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

job/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create-job/',views.create_job,name='create-job'),
    path('update-job/<int:pk>/',views.update_job,name='update-job'),
    path('delete-job/<int:pk>/',views.delete_job,name='delete-job'),
    path('accept-job/<int:app_pk>/',views.accept_job,name='accept-job'),
    path('reject-job/<int:app_pk>/',views.reject_job,name='reject-job'),
    path('manage-jobs/',views.manage_jobs,name='manage-jobs'),
    path('apply-to-job/<int:pk>/', views.apply_to_job, name= 'apply-to-job'),
    path('all-applicants/<int:pk>/', views.all_applicants, name='all-applicants'), 
    path('applied-jobs/', views.applied_jobs, name='applied-jobs'),
    path('delete-application/<int:job_pk>/' , views.delete_application, name = 'delete-application')
]

job/models.py
from django.db import models
from users.models import User
from company.models import Company
from resume.models import Resume
 

class Job(models.Model):
    job_type_choices = (
        ('Remote', 'Remote'),
        ('Onsite', 'Onsite'),
        ('Hybrid', 'Hybrid')
    )

    state_choices = (
        ('Karnataka', 'Karnataka'),
        ('Assam', 'Assam'),
        ('Gujarat', 'Gujarat'),
        ('Kashmir', 'Kashmir'),
        ('Tamil Nadu', 'Tamil Nadu'),
        ('Bihar', 'Bihar'),
        ('Uttar Pradesh', 'Uttar Pradesh')
    )

    industry_choices = (
        ('Technology', 'Technology'),
        ('Education', 'Education'),
        ('Transportation', 'Transportation'),
        ('Finance', 'Finance'),
        ('Healthcare', 'Healthcare'),
        ('Sports', 'Sports'),
        ('Energy', 'Energy')
    )
    
    title_choices = (
        ('Developer', 'Developer'),
        ('Consultant','Consultant'),
        ('Analyst' , 'Analyst'),
        ('Manager' , 'Manager'),
        ('UI/UX' , 'UI/UX'),
        ('Human Resource' , 'Human Resource'),
        ('Operations' , 'Operations')
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE) 
    title = models.CharField(max_length=100, choices = title_choices, null = True, blank = True)
    city = models.CharField(max_length=100)
    salary = models.PositiveIntegerField(default=35000)
    requirements = models.TextField()
    ideal_candidate = models.TextField()
    is_available = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    industry = models.CharField(max_length=20, choices=industry_choices, null=True, blank=True)
    state = models.CharField(max_length=20, choices=state_choices, null=True, blank=True)
    job_type = models.CharField(max_length=20, choices=job_type_choices, null=True, blank=True)

    def __str__(self):
        return self.title

class ApplyJob(models.Model):
    status_choices = (
        ('Accepted', 'Accepted'), 
        ('Declined', 'Declined'), 
        ('Pending', 'Pending')
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=status_choices)
    

job/forms.py
from django import forms
from .models import Job

class CreateJobForm(forms.ModelForm):
    class Meta:
        model = Job
        exclude = ('user', 'company')

class UpdateJobForm(forms.ModelForm):
    class Meta:
        model = Job
        exclude = ('user', 'company')

job/views.py
from difflib import context_diff
from django.shortcuts import render,redirect
from django.contrib import messages
from .models import Job,ApplyJob
from .forms import CreateJobForm,UpdateJobForm
from users.models import User 
from company.models import Company
from notifications.models import Notif
from resume.models import Resume
from django.core.mail import send_mail
from django.conf import settings



def create_job(request):
    if request.user.is_recruiter and request.user.has_company and request.user.is_verified: 
        if request.method == 'POST':
            form =  CreateJobForm(request.POST)
            if form.is_valid():
                var = form.save(commit=False)
                var.user = request.user
                var.company = request.user.company
                var.save()
                applicants = Resume.objects.filter(title = var.title)
                for applicant in applicants:
                    user = applicant.user
                    Notif.objects.create(
                        user = user,
                        content = "There is a new job opening for the role of <a href='/job-details/" + str(var.id) + "/'>" + str(var.title) + "</a> offered by" + str(var.company)
                    )
                    subject = 'There is a new job opening'
                    message = f'There is a new job opening for the role of {var.title} offered by {var.company}'
                    from_email = settings.EMAIL_HOST_USER
                    recipient_list = [user.email]
                    send_mail (subject , message , from_email , recipient_list)

                messages.info(request, 'New job has been created')
                return redirect('dashboard')
            else:
                messages.warning(request, 'Something went wrong')
                return redirect('create-job')
        else:
            form = CreateJobForm()
            context = {'form':form}
            return render(request, 'job/create_job.html', context)
    else:
        messages.warning(request, 'Permission Denied')
        return redirect('dashboard')


def update_job(request, pk):
    job = Job.objects.get(pk=pk)
    if request.user.is_authenticated and request.user.is_recruiter and request.user.is_verified and job.company.user == request.user:  #Ensure appropriate user given access
        if request.method == 'POST':
            form = UpdateJobForm(request.POST, instance=job)
            if form.is_valid():
                form.save()
                applicants = Resume.objects.filter(title = job.title)
                for applicant in applicants:
                    user = applicant.user
                    #notification
                    Notif.objects.create(
                        user = user,
                        content = "There has been an update in the job offer for the role of <a href='/job-details/" + str(job.id) + "/'>" + str(job.title) + "</a> offered by " + str(job.company)
                    )
                    subject = 'There has been an update in the job'
                    message = f'There has been an update in the job offer for the role of {job.title} offered by {job.company}'
                    from_email = settings.EMAIL_HOST_USER
                    recipient_list = [user.email]
                    send_mail (subject , message , from_email , recipient_list)
                messages.info(request, 'Your job info is updated')
                return redirect('dashboard')
            else:
                messages.warning(request, 'Something went wrong')
        else:
            form = UpdateJobForm(instance=job)
            context = {'form':form}
            return render(request, 'job/update_job.html', context)
    else:
        messages.warning(request, 'Permission Denied')
        return redirect('dashboard')



def _delete_job(job):
    applicants = Resume.objects.filter(title = job.title)
    for applicant in applicants:
        user = applicant.user
        Notif.objects.create(
        user = user,
        content = f'The job is no longer available for the role of {job.title} offered by {job.company}'
        )
        subject = 'There has been an update in the job'
        message = f'The job is no longer available for the role of {job.title} offered by {job.company}'
        from_email = settings.EMAIL_HOST_USER
        recipient_list = [user.email]
        send_mail (subject , message , from_email , recipient_list)

    job.delete()

def delete_job(request, pk):
    job = Job.objects.get(pk=pk)
    if request.user.is_authenticated and request.user.is_recruiter and request.user.is_verified and job.company.user == request.user:  #Ensure appropriate user given access
        _delete_job(job)
        messages.info(request, 'Your job is deleted')
        return redirect('manage-jobs')
    else:
        messages.warning(request, 'Permission Denied')
        return redirect('dashboard')



def manage_jobs(request):
    if request.user.is_authenticated and request.user.is_recruiter and request.user.is_verified:  #Ensure appropriate user given access
        jobs = Job.objects.filter(user=request.user, company=request.user.company)
        context = {'jobs':jobs}
        return render(request, 'job/manage_jobs.html', context)
    else:
        messages.info(request, 'Please Log In to Continue')
        return redirect('login')

def apply_to_job(request, pk):
    if request.user.is_authenticated and request.user.is_applicant and request.user.is_verified:    #user must be of applicant type to apply
        job = Job.objects.get(pk = pk)

        if ApplyJob.objects.filter(user = request.user, job = pk).exists():  #if user has already applied
            messages.warning(request, 'Permission Denied')
            return redirect('dashboard') 
        else:                           
            ApplyJob.objects.create(                            
                job = job,
                user = request.user,
                status = 'Pending'
            )
            applicant = Resume.objects.get(user=request.user)
            applicant = f'{applicant.first_name} {applicant.surname}'
            Notif.objects.create(
                user = job.company.user,
                content = f"{applicant} has applied to your company " + str(job.company) + " for the role of <a href='/job-details/" + str(job.id) + "/'>" + str(job.title) 
            )
            subject = 'Job Application Received'
            message = f'{applicant} has applied to your company {job.company} for the role of {job.title}'
            from_email = settings.EMAIL_HOST_USER
            recipient_list = [job.user.email]
            send_mail (subject , message , from_email , recipient_list)

            messages.info(request, 'You have successfully applied! Please see dashboard')
            return redirect('dashboard')
    else:
        messages.warning(request, 'Permission Denied')
        return redirect('dashboard')

        
def all_applicants(request, pk):
    job = Job.objects.get(pk=pk)

    if request.user.is_authenticated and request.user.is_recruiter and request.user.is_verified and job.company.user == request.user:  #Ensure appropriate user given access
        applied_jobs = ApplyJob.objects.filter(job = job)
        context = {'job':job, 'applied_jobs':applied_jobs}
        return render(request, 'job/all_applicants.html', context)
    else:
        messages.warning(request, 'Permission Denied')
        return redirect('dashboard')

def applied_jobs(request):
    if request.user.is_authenticated and request.user.is_applicant and request.user.is_verified:
        jobs = ApplyJob.objects.filter(user=request.user)
        context = {'jobs':jobs}
        return render(request, 'job/applied_job.html', context)
    else:
        messages.warning(request, 'Permission Denied')
        return redirect('dashboard')

    
def _delete_application(applicant_resume, pk):
    application = ApplyJob.objects.get(id = pk)
    Notif.objects.create(
        user = application.job.company.user,
        content = applicant_resume.__str__() + " has revoked their application for the role of <a href='/job-details/" + str(application.job.id) + "/'>" + str(application.job.title) + "</a>" + " from your company " + application.job.company.__str__()
    )   
    application.delete()

# def delete_application(request, job_pk):
#     if request.user.is_authenticated and request.user.is_applicant and request.user.is_verified:
#         job = Job.objects.get(pk=job_pk)
#         application = ApplyJob.objects.get(user = request.user, job = job)
#         if application.DoesNotExist:
#             messages.warning(request, 'Permission Denied')
#             return redirect('dashboard')
#         resume = Resume.objects.get(user = request.user)
#         _delete_application(resume, application.id)
#         messages.warning(request, 'Your application has been deleted')
#         return redirect('dashboard')
    
    
def delete_application(request, job_pk):
    if request.user.is_authenticated and request.user.is_applicant and request.user.is_verified and ApplyJob.objects.filter(user = request.user, job = job_pk).exists(): 
        job = Job.objects.get(pk=job_pk)
        application = ApplyJob.objects.get(user = request.user, job = job)
        resume = Resume.objects.get(user = request.user)
        _delete_application(resume, application.id)
        messages.warning(request, 'Your application has been deleted')
        return redirect('dashboard')
    else:
        messages.info(request, 'Something went wrong')
        return redirect('login')


def accept_job(request, app_pk):
    application = ApplyJob.objects.get(pk=app_pk)
    job = application.job


templates/job/all_applicants.html
{% extends 'base.html' %}

{% block content %}

<div class="card mx-auto" style="width: 76rem;">
    <!-- <img src="..." class="card-img-top" alt="..."> -->
    <div class="card-body">
        <h5 class="card-title mb-3">All Applicants for {{job.title}} Position</h5>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">First Name</th>
                    <th scope="col">Surname</th>
                    <th scope="col">Location</th>
                    <th scope="col">Job Position/Title</th>
                    <th scope="col">Application Date</th>
                    <th scope="col">Resume</th>
                    <th scope="col">Status</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for applied_job in applied_jobs %}
                <tr>
                    <td>{{applied_job.user.resume.first_name}}</td>
                    <td>{{applied_job.user.resume.surname}}</td>
                    <td>{{applied_job.user.resume.location}}</td>
                    <td>{{applied_job.user.resume.title}}</td>
                    <td>{{applied_job.timestamp}}</td>
                    {% if applied_job.user.resume and applied_job.user.resume.upload_resume.url %}
                    <td><a target="_blank" href="{{applicant.user.resume.upload_resume.url}}"><small>Download Resume</small></a></td>
                    {% else %}
                    <td>Resume not uploaded</td>
                    {% endif %}
                    <td>{{applied_job.status}}</td>
                    {% if not applied_job.job.is_available %}
                        <td>Job is not active</td>
                    {% elif applied_job.status == 'Pending' %}
                        <td><a href="{% url 'accept-job' applied_job.pk %}"><span class="badge bg-success">Accept</span></a>
                            <a href="{% url 'reject-job' applied_job.pk %}"><span class="badge bg-danger">Reject</span></a></td>
                    {% endif %}
                </tr>

                {% endfor %}
            </tbody>
        </table>

        <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
            card's content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a> -->
    </div>
</div>


{% endblock content %}

templates/job/applied_job.html
{% extends 'base.html' %}

{% block content %}

<div class="card mx-auto" style="width: 76rem;">
    <!-- <img src="..." class="card-img-top" alt="..."> -->
    <div class="card-body">
        <h5 class="card-title mb-3">Manage Jobs</h5>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">Job title</th>
                    <th scope="col">Location</th>
                    <th scope="col">Salary </th>
                    <th scope="col">Job Type</th>
                    <th scope="col">Industry</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for job in jobs %}
                <tr>
                    <td>{{job.job.title}}</td>
                    <td>{{job.job.city}}, {{job.job.state}}</td>
                    <td>{{job.job.salary}}</td>
					<td>{{job.job.job_type}}</td>
					<td>{{job.job.industry}}</td>
                    <td><a href="{% url 'job-details' job.job.pk %}"><small>Details</small></a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
            card's content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a> -->
    </div>
</div>


{% endblock content %}

templates/job/create_job.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load humanize %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        <div class="card mx-auto" style ="width: 40rem;">
            <!-- <img src ="..." class="card-img-top" alt="..."> -->
            <div class="card-body">
                <h5 class="card-title mb-3">Create A Job AD</h5>

                <form method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Job Title</label>
                        {% render_field form.title class="form-select" %}
                    </div>

                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Salary</label>
                        {% render_field form.salary class="form-control" %}
                    </div>
                    
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">City</label>
                        {% render_field form.city class="form-control" %}
                    </div>

                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">State</label>
                        {% render_field form.state class="form-control" %}
                    </div>

                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Industry</label>
                        {% render_field form.industry|attr:"rows:2" class="form-control" %}
                    </div>
                    
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Job Type</label>
                        {% render_field form.job_type class="form-control" %}
                    </div>
                    
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Job Requirements</label>
                        {% render_field form.requirements|attr:"rows:2" class="form-control" %}
                    </div>

                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Ideal candidate</label>
                        {% render_field form.ideal_candidate|attr:"rows:2" class="form-control" %}
                    </div>

                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Is this Job Available</label>
                        {% render_field form.is_available class="form-check-input" %}
                    </div>

                    <button type="submit" class = "btn btn-primary">Submit</button>
                </form>

                <!-- <p class ="card-text">Some quick example text to build on the card title and make up the bulk of card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a> -->
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/job/manage_jobs.html
{% extends 'base.html' %}

{% block content %}

<div class="card mx-auto" style="width: 76rem;">
    <!-- <img src="..." class="card-img-top" alt="..."> -->
    <div class="card-body">
        <h5 class="card-title mb-3">Manage Jobs</h5>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">Job title</th>
                    <th scope="col">Location</th>
                    <th scope="col">Salary </th>
                    <th scope="col">No. of Applicants</th>
                    <th scope="col">Status</th>
                    <th scope="col">Update</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for job in jobs %}
                <tr>
                    <td>{{job.title}}</td>
                    <td>{{job.city}}, {{job.state}}</td>
                    <td>{{job.salary}}</td>
                    <td>{{job.applyjob_set.all.count }} <a href="{% url 'all-applicants' job.pk %}"><small>View all</small></a></td> <!-- No. of Applicants Calc-->

                    {% if job.is_available %}
                    <td><span class="badge bg-success">Active</span></td>
                    {% else %}
                    <td><span class="badge bg-warning">Not Active</span></td>
                    {% endif %}
                     
                    <td><a href="{% url 'update-job' job.pk %}"><span class="badge bg-secondary">Update Job</span></a></td>
                    <td><a href="{% url 'delete-job' job.pk %}"><span class="badge bg-danger">Delete Job</span></a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        
    </div>
</div>


{% endblock content %}

templates/job/update_job.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load humanize %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        <div class="card mx-auto" style ="width: 40rem;">
            <!-- <img src ="..." class="card-img-top" alt="..."> -->
            <div class="card-body">
                <h5 class="card-title mb-3">Update Job</h5>

                <form method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Job Title</label>
                        {% render_field form.title class="form-control" %}
                    </div>

                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Salary</label>
                        {% render_field form.salary class="form-control" %}
                    </div>
                    
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">City</label>
                        {% render_field form.city class="form-control" %}
                    </div>

                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">State</label>
                        {% render_field form.state class="form-control" %}
                    </div>

                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Industry</label>
                        {% render_field form.industry class="form-control" %}
                    </div>
                    
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Job Type</label>
                        {% render_field form.job_type class="form-control" %}
                    </div>
                    
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Job Requirements</label>
                        {% render_field form.requirements|attr:"rows:2" class="form-control" %}
                    </div>

                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Ideal candidate</label>
                        {% render_field form.ideal_candidate|attr:"rows:2" class="form-control" %}
                    </div>

                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Is this Job Available</label>
                        {% render_field form.is_available class="form-check-input" %}
                    </div>

                    <button type="submit" class = "btn btn-primary">Submit</button>
                </form>

                <!-- <p class ="card-text">Some quick example text to build on the card title and make up the bulk of card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a> -->
            </div>
        </div>
    </div>
</div>

{% endblock content %}